// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeLink': string;
  'app-brand': string;
  'app-footer': string;
  'app-header': string;
  'app-nav': string;
  'app-wrapper': string;
  'appBrand': string;
  'appFooter': string;
  'appHeader': string;
  'appNav': string;
  'appWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
