// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeButton': string;
  'content': string;
  'modal': string;
  'new-chat-btn': string;
  'newChatBtn': string;
  'newChatForm': string;
  'room': string;
  'room-list': string;
  'roomList': string;
}
declare var cssExports: CssExports;
export = cssExports;
