// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'page-container': string;
  'pageContainer': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
